### ISSUE TITLE
XLDateAmbiguous: Error message could be better

### ISSUE THREAD

**Issue by joeflack4** [opendatakit/xlsform-online#13]
**Related to: ** https://github.com/XLSForm/pyxform/issues/228 & https://github.com/XLSForm/pyxform/issues/229
---
## Expected behavior
When encountering an ambiguous date and the error `XLDateAmbiguous` occurs, error message should ideally mention the location where the issue occurred.

## Actual behavior
Confusing error message with little information appears: `Error: 1.0`

**Example**
![xldateambiguous](https://user-images.githubusercontent.com/13045020/45761314-ff57e000-bbf9-11e8-9125-f99b338226a2.png)

---

**Attachments**
[XLDateAmbiguous-v1.xlsx.zip](https://github.com/XLSForm/pyxform/files/2397513/XLDateAmbiguous-v1.xlsx.zip)

**Comment by yanokwa** [comment]
Closing because this has been filed upstream. We should fix it there :)
