### ISSUE TITLE
Problem with "choice_filter"

### ISSUE THREAD

**Issue by mtyszler** [opendatakit/xlsform-online#26]
I'm afraid this commit created another issue. The decoration is converting "choice_filter" into "choice-filter", but that leads to a "list out of range" error when the "choice_filter" was active.

#24

**Comment by yanokwa** [comment]
Thanks for filing this. It's an issue with pyxform upstream and I've filed the upstream issue at https://github.com/XLSForm/pyxform/issues/352 and I'll close this one once upstream is fixed.

As a short term fix, I've rolled back to the previous version (v1.5.0)

**Comment by yanokwa** [comment]
@mtyszler I'm trying to track down the choice_filter issue and can't reproduce it. Do you have a sample form that you can share?

**Comment by mtyszler** [comment]
Hi @yanokwa ,

You can see the attached file. L1 has the field "choice_filter". Since you reverted the version we did not get the error anymore, but the file attached was triggering the error with "choice_filter", which was solved by replacing by "choice-filter" manually.

[Example_Problem.xlsx](https://github.com/opendatakit/xlsform-online/files/3558854/Example_Problem.xlsx)

**Comment by yanokwa** [comment]
I've been able to repro and filed the issue at https://github.com/XLSForm/pyxform/issues/355. Thanks for your help, @mtyszler!

**Comment by mtyszler** [comment]
Thank you for picking this up. Happy to contribute.

**Comment by yanokwa** [comment]
Fixed with #27
