### ISSUE TITLE
pyxform errors not shown properly

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/xlsform-online#5]
#### Software and hardware versions 
http://opendatakit.org/xiframe/

#### Problem description
When converting a form, pyxform errors are not displayed as expected.

#### Steps to reproduce the problem
1. Select a form that has an illegal name (starts with a number or has a space in it) such as 
[pyxform-errors.xlsx](https://github.com/opendatakit/xlsform-online/files/1636467/pyxform-errors.xlsx)
1. Convert it.
1. The error is `Error: Can't convert 'bytes' object to str implicitly`

#### Expected behavior
A pyxform error should be displayed: `[row : 2] Invalid question name [1field] Names must begin with a letter, colon, or underscore.Subsequent characters can include numbers, dashes, and periods.`

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment]
Appears to be fixed in the latest release! 👏 👏

**Comment by yanokwa** [comment]
Fixed
